### ISSUE TITLE
Data access still v9 style

### ISSUE THREAD

**Issue by wickermoon** [ruipin/fvtt-shared-library#1]
fvtt-shared-library still accesses modules and system data via v9 style ".data". v10 dropped the ".data" in favour of direct-access.

![image](https://user-images.githubusercontent.com/15907070/188278082-ca69c2f2-ce94-42db-a2a3-87db3de8b814.png)

**Comment by ruipin** [comment]
Updated the code with a version that is still compatible with v9 and older, but no longer has the warning in v10 or newer. Closing.

Thanks for your report!
